customer/api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='customer/change_password.html'), name='change-password'),
    path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(template_name='customer/change-password-done.html'), name='password_change_done')
]

customer/urls.py
from django.urls import path
from .views import register_customer, login_customer, profile, logout_customer, edit_profile, add_address, order_history

app_name = 'customer'
urlpatterns = [
    path('register/', register_customer, name='register'),
    path('login/', login_customer, name='login'),
    path('logout/', logout_customer, name='logout'),
    path('profile/', profile, name='profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path('add_address/', add_address, name='add_address'),
    path('order_history/', order_history, name='order_history')

]

order/urls.py
from django.urls import path

from order.views import order

app_name = 'order'
urlpatterns = [
    #path('cart_items/', cart_items, name='cart-items'),
    # path('order/<pk>', order, name='order')
]

store_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from product.views import index
from product.api.views import HomePagination

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePagination.as_view()),
    path('customer/', include('customer.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.api.urls')),
    path('api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

from account.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=11, unique=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Address(models.Model):
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f'نام:{self.customer.first_name} {self.customer.last_name} آدرس:{self.city} {self.street}'

customer/forms.py
from django import forms
from .models import Customer, Address


class RegisterCustomer(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='رمز عبور')

    class Meta:
        model = Customer
        exclude = ('user',)
        labels = {'first_name': 'نام', 'last_name': 'نام خانوادگی', 'email': 'ایمیل', 'phone': 'شماره تلفن'}


class LoginCustomer(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='رمز عبور')

    class Meta:
        model = Customer
        fields = ('email',)
        labels = {'email': 'ایمیل'}


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('city', 'street')

customer/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from account.models import User
from order.models import Order, OrderItem
from .forms import RegisterCustomer, LoginCustomer, AddressForm
from .models import Customer, Address


def register_customer(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        password = request.POST.get('password')

        create_user = User.objects.create_user(email=email, password=password)
        create_user.is_customer = True
        create_user.save()

        create_customer = Customer.objects.create(user=create_user, first_name=first_name, last_name=last_name, phone=phone)
        create_customer.save()
        login(request, create_user)

        return redirect('home')

    return render(request, 'customer/register_customer.html', context={})


def login_customer(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user:
            login(request, user)
            if 'next' in request.GET:
                return HttpResponseRedirect(request.GET['next'])
            return redirect('home')
        else:
            return HttpResponse('email or password is incorrect')

    return render(request, 'customer/login_customer.html', context={})


def logout_customer(request):
    logout(request)
    return redirect('home')


def profile(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    orderitems = OrderItem.objects.filter(order__customer__user_id=user.id)[:5]
    return render(request, 'customer/profile.html', context={'customer': customer, 'orderitems': orderitems})


def order_history(request):
    orderitems = OrderItem.objects.filter(order__customer__user_id=request.user.id)
    return render(request, 'customer/order_history.html', context={'orderitems': orderitems})



def edit_profile(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone = request.POST.get('phone')

        user = request.user
        customer = Customer.objects.get(user=user)

        customer.first_name = first_name
        customer.last_name = last_name
        customer.phone = phone
        customer.save()

        return redirect('customer:profile')

    return render(request, 'customer/edit_profile.html')


def add_address(request):
    if request.method == 'POST':
        customer = Customer.objects.get(user=request.user)
        form = AddressForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data.get('city')
            street = form.cleaned_data.get('street')
            new_address = Address.objects.create(customer=customer, city=city, street=street)
            new_address.save()
    else:
        form = AddressForm()

    return render(request, 'customer/add_address.html', context={'form': form})

customer/templates/customer/add_address.html
{% extends 'base.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="افزودن">
    </form>
{% endblock %}

customer/templates/customer/change-password-done.html
{% extends 'base.html' %}

{% block body %}
<div class="mt-5 text-center">
    <p class="alert alert-success font">
        <b>password changed successfully</b>
    </p>
</div>
{% endblock %}

customer/templates/customer/change_password.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="text-center mt-5 card">
        <h3 class="font text-info card-header"><b>تغییر رمز عبور</b></h3><br>
        <div class="card-body">
            <form method="post" novalidate>
                {% csrf_token %}
                <span class="font text-danger">
                    <b>
                        {{ form.old_password.errors }}
                    </b>
                </span>
                <span class="font">
                    <b>
                        <p>رمز قدیمی</p>
                    </b>
                </span>
                {{ form.old_password }}<br><br>
                <span class="font text-danger">
                    <b>
                        {{ form.new_password1.errors }}
                    </b>
                </span>
                <span class="font">
                    <b>
                        <p>رمز جدید</p>
                    </b>
                </span>
                {{ form.new_password1 }}<br><br>
                <span class="font text-danger">
                    <b>
                        {{ form.new_password2.errors }}
                    </b>
                </span>
                <span class="font">
                    <b>
                        <p>تکرار رمز</p>
                    </b>
                </span>
                {{ form.new_password2 }}<br><br>
                <button type="submit" class="btn btn-info font"><b>تغییر</b></button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

customer/templates/customer/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'customer/css/login_style.css' %}" />
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block body %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

				<form method="post" class="login100-form validate-form">
                    {% csrf_token %}
					<span class="login100-form-title p-b-26">
						ویرایش اطلاعات
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="first_name">
						<span class="focus-input100" data-placeholder="نام"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="text" name="last_name">
						<span class="focus-input100" data-placeholder="نام خانوادگی"></span>
					</div>

                    <div class="wrap-input100 validate-input">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="text" name="phone">
						<span class="focus-input100" data-placeholder="شماره تلفن"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								ذخیره تغییرات
							</button>
						</div>
					</div>

				</form>
			</div>
		</div>
	</div>
{% endblock %}

customer/templates/customer/login_customer.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'customer/css/login_style.css' %}" />
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

{% block navbar %}
{% endblock %}

{% block body %}

{#{% load crispy_forms_tags %}#}
{#    <h1 style="text-align: center; color: blue">ورود</h1>#}
{##}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        {{ form|crispy }}#}
{#        <input class="btn btn-success" type="submit" value="ورود">#}
{#    </form>#}


	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">

				<form method="post" class="login100-form validate-form">
                    {% csrf_token %}
					<span class="login100-form-title p-b-26">
						ورود
					</span>
					<span class="login100-form-title p-b-48">
						<i class="zmdi zmdi-font"></i>
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="email">
						<span class="focus-input100" data-placeholder="ایمیل"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<span class="btn-show-pass">
							<i class="zmdi zmdi-eye"></i>
						</span>
						<input class="input100" type="password" name="password">
						<span class="focus-input100" data-placeholder="رمز عبور"></span>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								ورود
							</button>
						</div>
					</div>

					<div class="text-center p-t-115">
						<span class="txt1">
							Don’t have an account?
						</span>

						<a class="txt2" href="{% url 'customer:register' %}">
							Sign Up
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

customer/templates/customer/order_history.html
{% extends 'base.html' %}

{% block body %}
     <div class="row">
            <div class="col-12">
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>#</th>
                            <th>محصول</th>
                            <th>تاریخ سفارش</th>
                            <th>آدرس</th>
                            <th>تعداد</th>
                            <th>وضعیت</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orderitems %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ order.product}}</td>
                                <td>{{ order.order.placed_at }}</td>
                                <td>{{ order.order.address }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>{{ order.order.payment_status }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

customer/templates/customer/profile.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

    <meta charset="UTF-8">
    <title>Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'customer/css/nav_panel_style.css' %}">
{% endblock %}


{% block body %}

    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'customer:edit_profile' %}">ویرایش اصلاعات شخصی</a>
        <a href="{% url 'change-password' %}">تغییر رمز عبور</a>
        <a href="{% url 'customer:add_address' %}">افزودن آدرس</a>
        <a href="{% url 'customer:order_history' %}">تاریخچه سفارشات</a>
    </div>

<div id="main">
  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
</div>

    <div class="container" style="padding-top: 4rem">
        <div class="row">
            <div class="col-12">
                <div class="row border-bottom">
                    <div class="col-lg-6 col-sm-12 border-right">
                        <p class="h3c">نام</p>
                        <h5 class="pc">{{ customer.first_name }}</h5>
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <p class="h3c">نام خانوادگی</p>
                        <h5 class="pc">{{ customer.last_name }}</h5>
                    </div>
                </div>
                <div class="row border-bottom">
                    <div class="col-lg-6 col-sm-12 border-right">
                        <p class="h3c">ایمیل</p>
                        <h5 class="pc">{{ user.email }}</h5>
                    </div>
                    <div class="col-lg-6 col-sm-12">
                        <p class="h3c">شماره تلفن</p>
                        <h5 class="pc">{{ customer.phone }}</h5>
                    </div>
                </div>
            </div>
        </div>
        <br><br><br>
    <h2 style="text-align: center">سفارشات اخیر</h2>
        <div class="row">
            <div class="col-12">
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>#</th>
                            <th>محصول</th>
                            <th>تاریخ سفارش</th>
                            <th>آدرس</th>
                            <th>تعداد</th>
                            <th>وضعیت</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in orderitems %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{ order.product}}</td>
                                <td>{{ order.order.placed_at }}</td>
                                <td>{{ order.order.address }}</td>
                                <td>{{ order.quantity }}</td>
                                <td>{{ order.order.payment_status }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    <div>


    </div>

    </div>
    </div>
{#</div>#}
{#    <div id="mySidenav" class="sidenav">#}
{#  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>#}
{#  <a href="#">About</a>#}
{#  <a href="#">Services</a>#}
{#  <a href="#">Clients</a>#}
{#  <a href="#">Contact</a>#}
{#</div>#}
{##}
{#<div id="main">#}
{#  <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>#}
{#</div>#}

    <script src="{% static 'customer/js/panel_nav.js' %}"></script>
{% endblock %}

customer/templates/customer/register_customer.html
{% extends 'base.html' %}

{% block body %}
{% load crispy_forms_tags %}
    <h1 style="text-align: center; color: blue">ثبت نام</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="ایجاد اکانت">
    </form>

{% endblock %}