order/urls.py
from django.urls import path

from order.views import order

app_name = 'order'
urlpatterns = [
    #path('cart_items/', cart_items, name='cart-items'),
    # path('order/<pk>', order, name='order')
]

product/api/urls.py
from django.urls import path

from product.api.views import HomePagination

urlpatterns = [
    path('', HomePagination.as_view(), name='home'),
]

product/urls.py
from django.urls import path

from .views import product_view_by_category #index,

app_name = 'product'
urlpatterns = [
   # path('index/', index, name='index'),
    path('category_products/<category>', product_view_by_category, name='category_products')
]

store_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from product.views import index
from product.api.views import HomePagination

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePagination.as_view()),
    path('customer/', include('customer.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.api.urls')),
    path('api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models

from store_project.utils import image_path_generator


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    is_exist = models.BooleanField(default=True)
    category = models.ManyToManyField(Category)
    image = models.ImageField(upload_to=image_path_generator, null=True, default=None, verbose_name='product images')

    def __str__(self):
        return self.name


class DiscountCode(models.Model):
    code_name = models.CharField(max_length=6)
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    percent = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.code_name} {self.product}'

product/api/views.py
from django.shortcuts import render
from django.views import View, generic

from product.models import Product, Category


class HomePagination(generic.ListView):
    template_name = 'product/index.html'
    queryset = Product.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        categories = Category.objects.all()
        products = Product.objects.all().order_by('is_exist')[:8]

        context = {
            'categories': categories,
            'products': products,
        }
        return context

product/views.py
from django.shortcuts import render
from product.models import Product, Category


def product_view_by_category(request, category):
    products = Product.objects.filter(category__name=category)
    return render(request, 'product/category_products.html', context={'products': products})

product/templates/product/category_products.html
{% extends 'base.html' %}

{% block body %}
    {% for product in products %}
        <div style="width: 307px;" class="product">
            <div style="text-align: center">
                <img src="{{ product.image.url }}" />
            </div>
            <h3 style="text-align: center">{{ product.name }}</h3>
            <p style="text-align: center">{{ product.description }}</p>
            <h6 style="position: relative; top: 25px; left: 80px">قیمت</h6>
            <h6 style="margin-left: 5px">{{ product.price }}</h6>
            <a style="position: relative; left: 55px" href="{% url 'cart' product.id%}" class="btn"><h5>افزودن به سبد خرید</h5></a>
        </div>
    {% endfor %}
{% endblock %}

product/templates/product/index.html
{% extends 'base.html' %}

{% block body %}
    <style>
        .close:hover,
        .close:focus {
          color: #000;
          text-decoration: none;
          cursor: pointer;
        }
        .modal {
            text-align: right;
            position: relative;
            top: 10px;
        }
    </style>
     <div class="navbar">
        <h6 id="category" style="margin-left: 1150px; margin-top: 5px">دسته بندی کالاها</h6>
        <i class="fa fa-bars"></i>
        <div id="myModal" class="modal">
            <div class="modal-content">
                <span style="margin-right: 25px" class="close">&times;</span>
                {% for category in categories %}
                <a href="{% url 'product:category_products' category.name %}"><h6 style="margin-right: 25px; margin-top: 10px; color: #000000">{{ category }}</h6></a>
                {% endfor %}

            </div>
        </div>
    </div>
    {% for product in products %}
        <div style="width: 307px; height: 424px" class="product">
            <div style="text-align: center">
                <img src="{{ product.image.url }}" />
            </div>
            <h3 style="text-align: center">{{ product.name.url }}</h3>
            <p style="text-align: center">{{ product.description }}</p>
            <h6 style="position: relative; top: 25px; left: 250px">قیمت</h6>
            <h6 style="margin-left: 170px">{{ product.price }}</h6>
            <a style="position: relative; left: 55px;top: 20px" href="{% url 'cart' product.id%}" class="btn btn-info"><h5>افزودن به سبد خرید</h5></a>
        </div>
    {% endfor %}

{% endblock %}