customer/api/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='customer/change_password.html'), name='change-password'),
    path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(template_name='customer/change-password-done.html'), name='password_change_done')
]

customer/urls.py
from django.urls import path
from .views import register_customer, login_customer, profile, logout_customer, edit_profile, add_address, order_history

app_name = 'customer'
urlpatterns = [
    path('register/', register_customer, name='register'),
    path('login/', login_customer, name='login'),
    path('logout/', logout_customer, name='logout'),
    path('profile/', profile, name='profile'),
    path('edit_profile', edit_profile, name='edit_profile'),
    path('add_address/', add_address, name='add_address'),
    path('order_history/', order_history, name='order_history')

]

order/urls.py
from django.urls import path

from order.views import order

app_name = 'order'
urlpatterns = [
    #path('cart_items/', cart_items, name='cart-items'),
    # path('order/<pk>', order, name='order')
]

store_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from product.views import index
from product.api.views import HomePagination

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePagination.as_view()),
    path('customer/', include('customer.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.api.urls')),
    path('api/', include('core.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models

from account.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=11, unique=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Address(models.Model):
    city = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def __str__(self):
        return f'نام:{self.customer.first_name} {self.customer.last_name} آدرس:{self.city} {self.street}'

customer/forms.py
from django import forms
from .models import Customer, Address


class RegisterCustomer(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='رمز عبور')

    class Meta:
        model = Customer
        exclude = ('user',)
        labels = {'first_name': 'نام', 'last_name': 'نام خانوادگی', 'email': 'ایمیل', 'phone': 'شماره تلفن'}


class LoginCustomer(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='رمز عبور')

    class Meta:
        model = Customer
        fields = ('email',)
        labels = {'email': 'ایمیل'}


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('city', 'street')

customer/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from account.models import User
from order.models import Order, OrderItem
from .forms import RegisterCustomer, LoginCustomer, AddressForm
from .models import Customer, Address


def register_customer(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        password = request.POST.get('password')

        create_user = User.objects.create_user(email=email, password=password)
        create_user.is_customer = True
        create_user.save()

        create_customer = Customer.objects.create(user=create_user, first_name=first_name, last_name=last_name, phone=phone)
        create_customer.save()
        login(request, create_user)

        return redirect('home')

    return render(request, 'customer/register_customer.html', context={})


def login_customer(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        if user:
            login(request, user)
            if 'next' in request.GET:
                return HttpResponseRedirect(request.GET['next'])
            return redirect('home')
        else:
            return HttpResponse('email or password is incorrect')

    return render(request, 'customer/login_customer.html', context={})


def logout_customer(request):
    logout(request)
    return redirect('home')


def profile(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    orderitems = OrderItem.objects.filter(order__customer__user_id=user.id)[:5]
    return render(request, 'customer/profile.html', context={'customer': customer, 'orderitems': orderitems})


def order_history(request):
    orderitems = OrderItem.objects.filter(order__customer__user_id=request.user.id)
    return render(request, 'customer/order_history.html', context={'orderitems': orderitems})



def edit_profile(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        phone = request.POST.get('phone')

        user = request.user
        customer = Customer.objects.get(user=user)

        customer.first_name = first_name
        customer.last_name = last_name
        customer.phone = phone
        customer.save()

        return redirect('customer:profile')

    return render(request, 'customer/edit_profile.html')


def add_address(request):
    if request.method == 'POST':
        customer = Customer.objects.get(user=request.user)
        form = AddressForm(request.POST)
        if form.is_valid():
            city = form.cleaned_data.get('city')
            street = form.cleaned_data.get('street')
            new_address = Address.objects.create(customer=customer, city=city, street=street)
            new_address.save()
    else:
        form = AddressForm()

    return render(request, 'customer/add_address.html', context={'form': form})

customer/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
{% block head %}
    <meta charset="UTF-8">
    <title>Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}
<style>

    .product {
        border-radius: 10px;
        margin-right: 15px;
        margin-top: 15px;
        float: right;
        box-shadow: rgba(0, 0, 0, 0.1) 0px 10px 50px;
    }

    .top-nav {
        background: gray;
    }

    .dropbtn {
      {#background-color: #3498DB;#}
      color: black;
      padding: 16px;
      font-size: 16px;
      border: none;
      cursor: pointer;
        margin-right: 10px;

}

.dropbtn:hover, .dropbtn:focus {
  background-color: #2980B9;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  overflow: auto;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown a:hover {background-color: #ddd;}

.show {display: block;}
</style>

</head>
<body>

{% block navbar %}
    <div class="navbar top-nav">
        <div class="search-nav">
            <form method="post">
                {% csrf_token %}
                <input name="search" type="search" placeholder="جستوجو" style="border-radius: 5px; height: 35px">
                <button class="btn btn-secondary " type="submit">پیداکن</button>
            </form>
        </div>

        <a href="{% url 'cart-items' %}"><i class="fa fa-shopping-cart" style="font-size:36px; margin-left: 890px; color: #333333"></i></a>



            {% if user.is_authenticated %}
                    <div class="dropdown">
                    <i onclick="myFunction()" style="font-size:30px" class='dropbtn fa'>&#xf007;</i>
                      <div id="myDropdown" class="dropdown-content">
                          {% if not user.is_admin %}
                        <a href="{% url 'customer:profile' %}">پروفایل</a>
                          {% endif %}
                        <a href="{% url 'customer:logout' %}">خروج</a>
                      </div>
                    </div>
{# style="font-size:30px; position:relative; top: -45px; left: 1170px"#}
            {% else %}
                <div class="dropdown">
                <i onclick="myFunction()" style="font-size:30px;" class='dropbtn fa'>&#xf007;</i>
                    <div id="myDropdown" class="dropdown-content">
                        <a href="/customer/login/">ورود</a>
                        <a href="/customer/register/">ثبت نام</a>
                    </div>
                </div>
            {% endif %}
    </div>

{% endblock %}

    {% block body %}{% endblock %}


<script>
    var modal = document.getElementById('myModal')
    var cat_click = document.getElementById('category')
    var span = document.getElementsByClassName('close')[0]

    cat_click.onclick = function () {
        modal.style.display = 'block'
    }

    span.onclick = function () {
        modal.style.display = 'none'
    }



/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
    function myFunction() {
      document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function(event) {
      if (!event.target.matches('.dropbtn')) {
        var dropdowns = document.getElementsByClassName("dropdown-content");
        var i;
        for (i = 0; i < dropdowns.length; i++) {
          var openDropdown = dropdowns[i];
          if (openDropdown.classList.contains('show')) {
            openDropdown.classList.remove('show');
          }
        }
      }
    }
</script>


</body>
</html>